// Generated by https://quicktype.io

export interface ProductHM {
  _links: Links;
  id: string;
  _fixed: boolean;
  shop_button_url: null;
  share_url: null;
  _embedded: ProductHMEmbedded;
  name: string;
  description: string;
  tag_based_key: string;
  product_url: string;
  hide_from_related: boolean;
  product_info: ProductInfo;
  status: string;
  _analytics: Analytics;
}

export interface Analytics {
  oid: string;
  t: string;
  meta: string[];
}

export interface ProductHMEmbedded {
  customer: Customer;
  base_image: BaseImage;
  cover_media: null;
  'media:recent': MediaMediaPositionClass;
  'media:shuffled': MediaMediaPositionClass;
  'media:photorank': MediaMediaPositionClass;
  'media:rated': MediaMediaPositionClass;
  'media:media_position': MediaMediaPositionClass;
}

export interface BaseImage {
  _links: Links;
  id: string;
  _fixed: boolean;
  type: string;
  source: string;
  source_id: null;
  original_source: null;
  caption: string;
  video_url: null;
  share_url: null;
  date_submitted: string;
  date_published: null;
  favorite: boolean;
  location: null;
  sonar_place: null;
  original_image_width: string;
  original_image_height: string;
  status: null;
  likes: number;
  request_id: null;
  images: Images;
  _embedded: BaseImageEmbedded;
  _forms: null;
  _analytics: Analytics;
}

export interface BaseImageEmbedded {
  uploader: null;
  'streams:all': null;
  'categories:all': null;
}

export interface Links {
  self: Self;
}

export interface Self {
  href: string;
}

export interface Images {
  square: string;
  thumbnail: string;
  mobile: string;
  normal: string;
  original: string;
}

export interface Customer {
  _links: Links;
  id: string;
  _fixed: boolean;
  name: string;
  domain: null;
  template_dir: string;
  language: string;
  settings: Settings;
  views: Views;
  _embedded: CustomerEmbedded;
  _forms: Forms;
}

export interface CustomerEmbedded {
  user: User;
  media: Media;
  'media:recent': Media;
  'media:shuffled': Media;
  'media:photorank': Media;
  'media:rated': Media;
}

export interface Media {
  _links: Links;
  _fixed: boolean;
}

export interface User {
  _links: Links;
  id: string;
  _fixed: boolean;
}

export interface Forms {
  'streams:search': CategoriesSearch;
  'categories:search': CategoriesSearch;
  'stashes:create': CategoriesSearch;
  'users:create': CategoriesSearch;
}

export interface CategoriesSearch {
  title: string;
  action: Self;
  method: string;
  fields: Field[];
}

export interface Field {
  type: string;
  prompt: string;
  name: string;
  value: string;
  placeholder: string;
}

export interface Settings {
  force_viewer_modal: boolean;
  column_number: string;
  items_per_page: number;
  uploader_actions: string;
  show_in_home: boolean;
  show_in_home_id: string;
  force_https: boolean;
  ab_testing: number;
  olapicU: string;
  customer_dependant: CustomerDependant;
  analytics_cookie_domain: string;
  premoderation: boolean;
  tagging: boolean;
  analytics_api_version: string;
  analytics_checkout_file_prefix: string;
  analytics_dashboard_engagement: boolean;
  analytics_conversion_interval: string;
  currency: string;
  analytics_enterprise_analytics: boolean;
  currency_info: CurrencyInfo;
  analytics_error_tracking: boolean;
  analytics_ga_integration: boolean;
  analytics_disabled: boolean;
}

export interface CurrencyInfo {
  code: string;
  symbol: string;
  name: string;
}

export interface CustomerDependant {
  viewer: string;
  widget: string;
  uploader: string;
  assets2: string;
}

export interface Views {
  viewer: string;
  uploader: string;
}

export interface MediaMediaPositionClass {
  _links: Links;
}

export interface ProductInfo {
  price: string;
  availability: string;
  stock: string;
  color: string;
}
